-- GWX-005.4 — Clean replacement for the rewritten activeSlot migrations
--
-- Replaces the two GWX-005.1/005.2 migrations that were edited after being
-- applied (20260421031417 and 20260423000001). Those files had checksum drift
-- and a timestamp-ordering bug that made fresh replay fragile. They have been
-- deleted from the migration directory and their _prisma_migrations rows
-- removed. This file is their single, immutable, canonical replacement.
--
-- What this migration does:
--   1. Adds activeSlot (nullable integer, default 1) to BackgroundJob
--   2. Backfills terminal rows to NULL to release the unique slot
--   3. Creates a unique index on (bidId, jobType, activeSlot)
--
-- Semantics:
--   activeSlot = 1   → job is active (queued or running); holds the unique slot
--   activeSlot = NULL → job is terminal (complete/failed/cancelled); slot released
--
-- SQLite unique index behaviour: NULL values are treated as distinct from each
-- other, so multiple terminal rows for the same (bidId, jobType) coexist safely.
-- Only the non-NULL value 1 is subject to uniqueness enforcement.
--
-- SQL generated by: prisma migrate diff --from-migrations --to-schema (schema-only)
-- Backfill UPDATE added manually (Prisma diff is schema-only, not data).

-- AlterTable
ALTER TABLE "BackgroundJob" ADD COLUMN "activeSlot" INTEGER DEFAULT 1;

-- Backfill: terminal jobs must release the slot
UPDATE "BackgroundJob" SET "activeSlot" = NULL WHERE "status" IN ('complete', 'failed', 'cancelled');

-- CreateIndex
CREATE UNIQUE INDEX "BackgroundJob_bidId_jobType_activeSlot_key" ON "BackgroundJob"("bidId", "jobType", "activeSlot");
