import type { Metadata } from "next";
import Link from "next/link";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <nav className="border-b border-zinc-200 bg-white">
          <div className="max-w-5xl mx-auto px-4 flex items-center gap-6 h-12">
            <span className="font-semibold text-sm tracking-tight">Bid Dashboard</span>
            <Link href="/bids" className="text-sm text-zinc-500 hover:text-zinc-900">
              Bids
            </Link>
            <Link href="/subcontractors" className="text-sm text-zinc-500 hover:text-zinc-900">
              Subcontractors
            </Link>
            <Link href="/outreach" className="text-sm text-zinc-500 hover:text-zinc-900">
              Outreach
            </Link>
            <Link href="/reports" className="text-sm text-zinc-500 hover:text-zinc-900">
              Reports
            </Link>
            <Link href="/settings/ai-tokens" className="ml-auto text-sm text-zinc-500 hover:text-zinc-900">
              Settings
            </Link>
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
