#!/usr/bin/env -S node --import=tsx

import { createHash, randomUUID } from "node:crypto";
import { constants as fsConstants, promises as fs } from "node:fs";
import path, { resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { meetingAudioStorageKey } from "@/lib/services/meetings/storagePath";
import { safeBlobFileName, type BlobStore } from "@/lib/storage/blobStore";

export const FIXTURE_VERSION = "gwx-mi-v2-staging-permanent-v1";
export const FIXTURE_CLASSIFICATION = "SYNTHETIC_STAGING_PERMANENT";
export const FIXTURE_BID_NAME =
  "[STAGING FIXTURE][MI-V2][PERMANENT] NON-CUSTOMER TASKING PROOF";
export const FIXTURE_MEETING_TITLE =
  "[STAGING FIXTURE][MI-V2][PERMANENT] SYNTHETIC MEDIA";
export const FIXTURE_LOCATION = "SYNTHETIC STAGING FIXTURE — NO CUSTOMER DATA";
export const FIXTURE_MEDIA_FILE_NAME = "gwx-mi-v2-synthetic-silence-v1.wav";
export const FIXTURE_CONFIRMATION_PHRASE =
  "I UNDERSTAND THIS CREATES PERMANENT MEETING INTELLIGENCE FIXTURE HISTORY";
export const FIXTURE_ENABLE_ENV = "MEETING_INTELLIGENCE_FIXTURE_SEEDING_ENABLED";
export const FIXTURE_ENABLE_VALUE = "1";
export const FIXTURE_AUDIT_ACTION = "meeting_intelligence_fixture_media_seeded";

const FIXTURE_BID_DESCRIPTION =
  "Permanent governed staging fixture generated by the Meeting Intelligence fixture seeder.";
const FIXTURE_BID_SCOPE = "SYNTHETIC_STAGING_PERMANENT — NO CUSTOMER DATA";
const FIXTURE_MEETING_DATE = new Date("2000-01-01T00:00:00.000Z");
const PREFIX = "[meeting-intelligence-staging-fixture]";
const SHA_PATTERN = /^[0-9a-f]{40}$/;

export type ParsedArgs = {
  seed: boolean;
  apply: boolean;
  dryRun: boolean;
  expectedRevision?: string;
  confirm?: string;
  manifest?: string;
  help: boolean;
  errors: string[];
};

type FixtureBid = {
  id: number;
  projectName: string;
  location: string | null;
  description: string | null;
  scope: string;
  status: string;
  workflowType: string;
};

type FixtureMeeting = {
  id: number;
  bidId: number;
  title: string;
  meetingDate: Date;
  meetingType: string;
  location: string | null;
  status: string;
  audioStorageKey: string | null;
  audioFileName: string | null;
  processingMode: string;
  uploadedAt: Date | null;
};

type FixtureAudit = {
  id: string;
  payloadJson: string | null;
  emittedAt: Date;
};

type TransactionClient = {
  bid: {
    findMany(args: unknown): Promise<FixtureBid[]>;
    create(args: unknown): Promise<FixtureBid>;
  };
  meeting: {
    findMany(args: unknown): Promise<FixtureMeeting[]>;
    create(args: unknown): Promise<FixtureMeeting>;
    update(args: unknown): Promise<FixtureMeeting>;
  };
  auditEvent: {
    findMany(args: unknown): Promise<FixtureAudit[]>;
    create(args: unknown): Promise<FixtureAudit>;
  };
};

type PrismaClientLike = {
  $transaction<T>(fn: (tx: TransactionClient) => Promise<T>): Promise<T>;
  meeting: {
    findFirst(args: unknown): Promise<{ id: number } | null>;
  };
};

export type SeederDependencies = {
  prisma: PrismaClientLike;
  blobStore: BlobStore;
};

type RuntimeEnvironment = Record<string, string | undefined>;

type SeedResult = {
  outcome: "created" | "already_present";
  bidId: number;
  meetingId: number;
  auditId: string;
  seededAt: string;
  seedApplicationRevision: string;
  mediaSha256: string;
  mediaBytes: number;
};

type FixtureManifest = {
  schemaVersion: 1;
  fixtureVersion: string;
  classification: string;
  bidId: number;
  meetingId: number;
  auditEventId: string;
  mediaFileName: string;
  mediaBytes: number;
  mediaSha256: string;
  seedApplicationRevision: string;
  seededAt: string;
};

class GateRefusal extends Error {}
class FixtureCollision extends Error {}
class CleanupProofFailure extends Error {}

function log(message: string): void {
  console.log(`${PREFIX} ${message}`);
}

function err(message: string): void {
  console.error(`${PREFIX} ${message}`);
}

const HELP_TEXT = `
meeting-intelligence-staging-fixture — governed staging-only permanent fixture seeder

Default behavior is a dry run. It performs no Prisma or BlobStore operation.

Apply the one canonical fixture:
  npm run seed:meeting-intelligence-staging-fixture -- \\
    --seed --apply \\
    --expected-revision <full-40-character-git-sha> \\
    --manifest <absolute-output-path> \\
    --confirm "${FIXTURE_CONFIRMATION_PHRASE}"

Inside the deployed app container, invoke the bundled runtime artifact with:
  node scripts/meeting-intelligence-staging-fixture.mjs <the same flags>

Required runtime gates:
  APP_ENV=staging
  ${FIXTURE_ENABLE_ENV}=${FIXTURE_ENABLE_VALUE}
  DATABASE_URL positively classified as the staging database
  APP_IMAGE_REVISION equal to --expected-revision

The command accepts no media path. It always generates the fixed synthetic WAV in memory.
There is no cleanup, purge, delete, or general-purpose fixture mode.
`;

export function parseArgv(argv: string[]): ParsedArgs {
  const parsed: ParsedArgs = {
    seed: false,
    apply: false,
    dryRun: false,
    help: false,
    errors: [],
  };

  const takeValue = (index: number, flag: string): string | undefined => {
    const value = argv[index + 1];
    if (value === undefined || value.startsWith("--")) {
      parsed.errors.push(`${flag} requires a value.`);
      return undefined;
    }
    return value;
  };

  for (let index = 0; index < argv.length; index += 1) {
    const arg = argv[index];
    if (arg === "--seed") parsed.seed = true;
    else if (arg === "--apply") parsed.apply = true;
    else if (arg === "--dry-run") parsed.dryRun = true;
    else if (arg === "--help" || arg === "-h") parsed.help = true;
    else if (arg === "--expected-revision") {
      parsed.expectedRevision = takeValue(index, arg);
      if (parsed.expectedRevision !== undefined) index += 1;
    } else if (arg === "--confirm") {
      parsed.confirm = takeValue(index, arg);
      if (parsed.confirm !== undefined) index += 1;
    } else if (arg === "--manifest") {
      parsed.manifest = takeValue(index, arg);
      if (parsed.manifest !== undefined) index += 1;
    } else if (
      arg === "--media-path" ||
      arg === "--audio-path" ||
      arg === "--file" ||
      arg === "--upload"
    ) {
      parsed.errors.push("Operator-provided media is prohibited; media is generated in memory.");
      if (argv[index + 1] !== undefined && !argv[index + 1].startsWith("--")) index += 1;
    } else if (arg === "--cleanup" || arg === "--purge" || arg === "--delete") {
      parsed.errors.push("Cleanup, purge, and delete capabilities are intentionally unavailable.");
    } else {
      parsed.errors.push(`Unknown option at argument position ${index + 1}.`);
    }
  }

  return parsed;
}

export type DatabaseClassification = "staging" | "production" | "ambiguous";

export function classifyDatabaseTarget(databaseUrl: string | undefined): DatabaseClassification {
  if (!databaseUrl) return "ambiguous";
  const lowered = databaseUrl.toLowerCase();
  let parsed: URL;
  try {
    parsed = new URL(databaseUrl);
  } catch {
    return /groundworx-prod|production/.test(lowered) ? "production" : "ambiguous";
  }

  const hostname = parsed.hostname.toLowerCase();
  const hasStagingMarker = hostname.includes("groundworx-staging");
  const hasProductionMarker =
    hostname.includes("groundworx-prod") ||
    hostname.includes("production") ||
    /groundworx-prod|production/.test(`${parsed.pathname}${parsed.search}`.toLowerCase());

  if (hasStagingMarker && hasProductionMarker) return "ambiguous";
  if (hasProductionMarker) return "production";
  if (!hasStagingMarker) return "ambiguous";
  if (parsed.protocol !== "libsql:" && parsed.protocol !== "https:") return "ambiguous";
  return "staging";
}

/** Deterministic one-second, 16 kHz, mono, signed-16-bit little-endian silent PCM WAV. */
export function buildSyntheticWav(): Buffer {
  const sampleRate = 16_000;
  const channels = 1;
  const bitsPerSample = 16;
  const sampleCount = sampleRate;
  const dataBytes = sampleCount * channels * (bitsPerSample / 8);
  const wav = Buffer.alloc(44 + dataBytes, 0);

  wav.write("RIFF", 0, "ascii");
  wav.writeUInt32LE(36 + dataBytes, 4);
  wav.write("WAVE", 8, "ascii");
  wav.write("fmt ", 12, "ascii");
  wav.writeUInt32LE(16, 16);
  wav.writeUInt16LE(1, 20);
  wav.writeUInt16LE(channels, 22);
  wav.writeUInt32LE(sampleRate, 24);
  wav.writeUInt32LE(sampleRate * channels * (bitsPerSample / 8), 28);
  wav.writeUInt16LE(channels * (bitsPerSample / 8), 32);
  wav.writeUInt16LE(bitsPerSample, 34);
  wav.write("data", 36, "ascii");
  wav.writeUInt32LE(dataBytes, 40);
  return wav;
}

export function syntheticWavSha256(): string {
  return createHash("sha256").update(buildSyntheticWav()).digest("hex");
}

function assertApplyGates(args: ParsedArgs, runtimeEnv: RuntimeEnvironment): string {
  if (!args.seed) throw new GateRefusal("--seed is required with --apply.");
  if (args.dryRun) throw new GateRefusal("--apply and --dry-run cannot be combined.");
  if (runtimeEnv.APP_ENV !== "staging") {
    throw new GateRefusal("APP_ENV check failed; expected staging.");
  }
  if (runtimeEnv[FIXTURE_ENABLE_ENV] !== FIXTURE_ENABLE_VALUE) {
    throw new GateRefusal(`Fixture seeding is disabled; set ${FIXTURE_ENABLE_ENV}=1 explicitly.`);
  }
  if (args.confirm !== FIXTURE_CONFIRMATION_PHRASE) {
    throw new GateRefusal("Confirmation phrase is missing or incorrect.");
  }
  if (!args.expectedRevision || !SHA_PATTERN.test(args.expectedRevision)) {
    throw new GateRefusal("--expected-revision must be a lowercase full 40-character Git SHA.");
  }
  const runtimeRevision = runtimeEnv.APP_IMAGE_REVISION;
  if (!runtimeRevision || !SHA_PATTERN.test(runtimeRevision)) {
    throw new GateRefusal("Runtime image revision is missing or untraceable.");
  }
  if (runtimeRevision !== args.expectedRevision) {
    throw new GateRefusal("Expected application revision does not match the runtime image revision.");
  }
  if (!args.manifest || !path.isAbsolute(args.manifest)) {
    throw new GateRefusal("--manifest must be an absolute output path.");
  }

  const databaseClassification = classifyDatabaseTarget(runtimeEnv.DATABASE_URL);
  if (databaseClassification === "production") {
    throw new GateRefusal("Database target is production-classified; refusing.");
  }
  if (databaseClassification !== "staging") {
    throw new GateRefusal("Database target is not positively staging-classified; refusing.");
  }
  return runtimeRevision;
}

function fixtureBidMatches(bid: FixtureBid): boolean {
  return (
    bid.projectName === FIXTURE_BID_NAME &&
    bid.location === FIXTURE_LOCATION &&
    bid.description === FIXTURE_BID_DESCRIPTION &&
    bid.scope === FIXTURE_BID_SCOPE &&
    bid.status === "awarded" &&
    bid.workflowType === "PROJECT"
  );
}

function fixtureMeetingMatches(meeting: FixtureMeeting, bidId: number): boolean {
  return (
    meeting.bidId === bidId &&
    meeting.title === FIXTURE_MEETING_TITLE &&
    meeting.meetingDate.toISOString() === FIXTURE_MEETING_DATE.toISOString() &&
    meeting.meetingType === "GENERAL" &&
    meeting.location === FIXTURE_LOCATION &&
    meeting.status === "PENDING" &&
    meeting.processingMode === "AUTO"
  );
}

function parseAuditPayload(audit: FixtureAudit): Record<string, unknown> | null {
  if (!audit.payloadJson) return null;
  try {
    const parsed = JSON.parse(audit.payloadJson) as unknown;
    return parsed !== null && typeof parsed === "object" && !Array.isArray(parsed)
      ? (parsed as Record<string, unknown>)
      : null;
  } catch {
    return null;
  }
}

function auditMatches(
  audit: FixtureAudit,
  bidId: number,
  meetingId: number,
  checksum: string,
  byteCount: number,
): audit is FixtureAudit {
  const payload = parseAuditPayload(audit);
  return (
    payload?.fixtureVersion === FIXTURE_VERSION &&
    payload.classification === FIXTURE_CLASSIFICATION &&
    payload.bidId === bidId &&
    payload.meetingId === meetingId &&
    payload.mediaFileName === FIXTURE_MEDIA_FILE_NAME &&
    payload.mediaSha256 === checksum &&
    payload.mediaBytes === byteCount &&
    typeof payload.applicationRevision === "string" &&
    SHA_PATTERN.test(payload.applicationRevision)
  );
}

function seedRevisionFromAudit(audit: FixtureAudit): string {
  const revision = parseAuditPayload(audit)?.applicationRevision;
  if (typeof revision !== "string" || !SHA_PATTERN.test(revision)) {
    throw new FixtureCollision("Fixture audit revision is invalid.");
  }
  return revision;
}

async function loadDefaultDependencies(): Promise<SeederDependencies> {
  const [{ prisma }, { getBlobStore }] = await Promise.all([
    import("@/lib/prisma"),
    import("@/lib/storage/blobStore"),
  ]);
  return {
    prisma: prisma as unknown as PrismaClientLike,
    blobStore: getBlobStore(),
  };
}

async function createOrVerifyFixture(
  deps: SeederDependencies,
  runtimeRevision: string,
): Promise<SeedResult> {
  const media = buildSyntheticWav();
  const mediaSha256 = createHash("sha256").update(media).digest("hex");
  const mediaFileName = safeBlobFileName(FIXTURE_MEDIA_FILE_NAME);
  let allocatedKey: string | null = null;
  let blobWriteAttempted = false;
  let transactionCommitted = false;

  try {
    const result = await deps.prisma.$transaction(async (tx) => {
      const bids = await tx.bid.findMany({
        where: { projectName: FIXTURE_BID_NAME },
        take: 2,
      });
      if (bids.length > 1) {
        throw new FixtureCollision("Multiple canonical fixture Bid labels exist.");
      }

      if (bids.length === 1) {
        const bid = bids[0];
        if (!fixtureBidMatches(bid)) {
          throw new FixtureCollision("The canonical Bid label belongs to a non-fixture record.");
        }
        const meetings = await tx.meeting.findMany({
          where: { bidId: bid.id, title: FIXTURE_MEETING_TITLE },
          take: 2,
        });
        if (meetings.length !== 1 || !fixtureMeetingMatches(meetings[0], bid.id)) {
          throw new FixtureCollision("Canonical fixture Meeting identity is missing or ambiguous.");
        }
        const meeting = meetings[0];
        const expectedKey = meetingAudioStorageKey(
          bid.id,
          meeting.id,
          FIXTURE_VERSION,
          mediaFileName,
        );
        if (
          meeting.audioStorageKey !== expectedKey ||
          meeting.audioFileName !== mediaFileName ||
          meeting.uploadedAt === null
        ) {
          throw new FixtureCollision("Existing fixture media pointer does not exactly match.");
        }

        const audits = await tx.auditEvent.findMany({
          where: {
            action: FIXTURE_AUDIT_ACTION,
            subjectKind: "Meeting",
            subjectId: String(meeting.id),
          },
          orderBy: { emittedAt: "asc" },
          take: 2,
        });
        if (audits.length !== 1 || !auditMatches(audits[0], bid.id, meeting.id, mediaSha256, media.length)) {
          throw new FixtureCollision("Existing fixture lacks one exact seeder audit marker.");
        }

        const stat = await deps.blobStore.stat(expectedKey);
        if (!stat || stat.sha256 !== mediaSha256 || stat.size !== media.length) {
          throw new FixtureCollision("Existing fixture media checksum or size does not match.");
        }
        return {
          outcome: "already_present" as const,
          bidId: bid.id,
          meetingId: meeting.id,
          auditId: audits[0].id,
          seededAt: audits[0].emittedAt.toISOString(),
          seedApplicationRevision: seedRevisionFromAudit(audits[0]),
          mediaSha256,
          mediaBytes: media.length,
        };
      }

      const bid = await tx.bid.create({
        data: {
          projectName: FIXTURE_BID_NAME,
          location: FIXTURE_LOCATION,
          description: FIXTURE_BID_DESCRIPTION,
          scope: FIXTURE_BID_SCOPE,
          status: "awarded",
          workflowType: "PROJECT",
        },
      });
      let meeting = await tx.meeting.create({
        data: {
          bidId: bid.id,
          title: FIXTURE_MEETING_TITLE,
          meetingDate: FIXTURE_MEETING_DATE,
          meetingType: "GENERAL",
          location: FIXTURE_LOCATION,
          status: "PENDING",
          processingMode: "AUTO",
        },
      });
      allocatedKey = meetingAudioStorageKey(bid.id, meeting.id, FIXTURE_VERSION, mediaFileName);

      if (await deps.blobStore.stat(allocatedKey)) {
        throw new FixtureCollision("Canonical fixture BlobStore key is already occupied.");
      }
      blobWriteAttempted = true;
      const put = await deps.blobStore.put(allocatedKey, media, { contentType: "audio/wav" });
      if (put.sha256 !== mediaSha256 || put.size !== media.length) {
        throw new FixtureCollision("BlobStore did not confirm the expected synthetic media identity.");
      }

      meeting = await tx.meeting.update({
        where: { id: meeting.id },
        data: {
          audioStorageKey: allocatedKey,
          audioFileName: mediaFileName,
          uploadedAt: new Date(),
        },
      });
      const audit = await tx.auditEvent.create({
        data: {
          category: "register_action",
          action: FIXTURE_AUDIT_ACTION,
          severity: "NOTICE",
          subjectKind: "Meeting",
          subjectId: String(meeting.id),
          actorKind: "operator",
          schemaVersion: "1.0",
          decision: "seeded",
          reasonLog: JSON.stringify(["governed_staging_fixture", "synthetic_non_customer_media"]),
          payloadJson: JSON.stringify({
            fixtureVersion: FIXTURE_VERSION,
            classification: FIXTURE_CLASSIFICATION,
            bidId: bid.id,
            meetingId: meeting.id,
            mediaFileName,
            mediaBytes: media.length,
            mediaSha256,
            applicationRevision: runtimeRevision,
          }),
        },
      });
      return {
        outcome: "created" as const,
        bidId: bid.id,
        meetingId: meeting.id,
        auditId: audit.id,
        seededAt: audit.emittedAt.toISOString(),
        seedApplicationRevision: runtimeRevision,
        mediaSha256,
        mediaBytes: media.length,
      };
    });
    transactionCommitted = true;
    return result;
  } catch (caught) {
    if (blobWriteAttempted && allocatedKey && !transactionCommitted) {
      let reference: { id: number } | null;
      try {
        reference = await deps.prisma.meeting.findFirst({
          where: { audioStorageKey: allocatedKey },
          select: { id: true },
        });
      } catch {
        throw new CleanupProofFailure("Unable to prove the failed write is unreferenced.");
      }
      if (reference === null) {
        try {
          await deps.blobStore.delete(allocatedKey);
        } catch {
          throw new CleanupProofFailure("Unable to clean the unreferenced failed fixture blob.");
        }
      }
    }
    throw caught;
  }
}

function buildManifest(result: SeedResult): FixtureManifest {
  return {
    schemaVersion: 1,
    fixtureVersion: FIXTURE_VERSION,
    classification: FIXTURE_CLASSIFICATION,
    bidId: result.bidId,
    meetingId: result.meetingId,
    auditEventId: result.auditId,
    mediaFileName: FIXTURE_MEDIA_FILE_NAME,
    mediaBytes: result.mediaBytes,
    mediaSha256: result.mediaSha256,
    seedApplicationRevision: result.seedApplicationRevision,
    seededAt: result.seededAt,
  };
}

async function writeManifestSecurely(manifestPath: string, manifest: FixtureManifest): Promise<void> {
  const parent = path.dirname(manifestPath);
  const parentStat = await fs.stat(parent);
  if (!parentStat.isDirectory()) throw new GateRefusal("Manifest parent is not a directory.");

  const content = `${JSON.stringify(manifest, null, 2)}\n`;
  try {
    const existingStat = await fs.lstat(manifestPath);
    if (!existingStat.isFile() || existingStat.isSymbolicLink()) {
      throw new GateRefusal("Manifest destination already exists and is not a regular file.");
    }
    const existing = await fs.readFile(manifestPath, "utf8");
    if (existing !== content) {
      throw new GateRefusal("Manifest destination already contains different evidence.");
    }
    await fs.chmod(manifestPath, 0o600);
    return;
  } catch (caught) {
    if ((caught as NodeJS.ErrnoException).code !== "ENOENT") throw caught;
  }

  const temporaryPath = path.join(
    parent,
    `.${path.basename(manifestPath)}.${process.pid}.${randomUUID()}.tmp`,
  );
  let handle: Awaited<ReturnType<typeof fs.open>> | null = null;
  try {
    handle = await fs.open(
      temporaryPath,
      fsConstants.O_CREAT | fsConstants.O_EXCL | fsConstants.O_WRONLY,
      0o600,
    );
    await handle.writeFile(content, "utf8");
    await handle.sync();
    await handle.close();
    handle = null;
    await fs.link(temporaryPath, manifestPath);
    await fs.chmod(manifestPath, 0o600);
  } finally {
    if (handle) await handle.close().catch(() => undefined);
    await fs.unlink(temporaryPath).catch((caught) => {
      if ((caught as NodeJS.ErrnoException).code !== "ENOENT") throw caught;
    });
  }
}

const MAX_ERROR_DESCRIPTOR_LENGTH = 64;
const ERRNO_CODE_PATTERN = /^[A-Z][A-Z0-9_]*$/;

export function sanitizeErrorDescriptor(caught: unknown): string {
  const code =
    caught && typeof caught === "object" && "code" in caught
      ? (caught as { code?: unknown }).code
      : undefined;
  if (typeof code === "string" && ERRNO_CODE_PATTERN.test(code)) {
    return code.slice(0, MAX_ERROR_DESCRIPTOR_LENGTH);
  }
  if (caught instanceof Error) {
    return caught.constructor.name.slice(0, MAX_ERROR_DESCRIPTOR_LENGTH);
  }
  return typeof caught;
}

function printPlan(): void {
  log("DRY RUN — fixture seeding remains disabled and no Prisma or BlobStore calls will be made.");
  log("Would create or verify one permanent, unmistakably labeled synthetic Bid and Meeting.");
  log("Would generate a deterministic one-second silent WAV, write it through BlobStore, and leave the Meeting PENDING.");
  log("Would append one durable audit event and write a mode-0600 non-secret manifest.");
  log("Stop on any environment, revision, database classification, identity, media, audit, or manifest collision.");
}

export async function runMain(
  argv: string[],
  options: {
    env?: RuntimeEnvironment;
    dependencies?: SeederDependencies;
  } = {},
): Promise<number> {
  const args = parseArgv(argv);
  if (args.help) {
    console.log(HELP_TEXT);
    return 0;
  }
  if (args.errors.length > 0) {
    for (const message of args.errors) err(message);
    return 1;
  }
  if (!args.apply) {
    printPlan();
    return 0;
  }

  try {
    const runtimeEnv = options.env ?? process.env;
    const runtimeRevision = assertApplyGates(args, runtimeEnv);
    log("Staging environment, explicit enablement, runtime revision, and database classification: PASS.");
    const dependencies = options.dependencies ?? (await loadDefaultDependencies());
    const result = await createOrVerifyFixture(dependencies, runtimeRevision);
    await writeManifestSecurely(args.manifest!, buildManifest(result));
    log(
      `${result.outcome === "created" ? "Fixture created" : "Fixture already present"}. ` +
        `bidId=${result.bidId} meetingId=${result.meetingId} mediaSha256=${result.mediaSha256}`,
    );
    log("Manifest evidence written with mode 0600. No queue or provider action was invoked.");
    return 0;
  } catch (caught) {
    if (caught instanceof GateRefusal || caught instanceof FixtureCollision) {
      err(caught.message);
      return 1;
    }
    err(`Unexpected failure: ${sanitizeErrorDescriptor(caught)}`);
    return 2;
  }
}

const invokedAsScript =
  typeof process !== "undefined" &&
  !!process.argv[1] &&
  resolve(process.argv[1]) === resolve(fileURLToPath(import.meta.url));

if (invokedAsScript) {
  runMain(process.argv.slice(2))
    .then((code) => {
      process.exitCode = code;
    })
    .catch((caught) => {
      err(`Unexpected bootstrap failure: ${sanitizeErrorDescriptor(caught)}`);
      process.exitCode = 2;
    });
}
